version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 340197286661.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Building Spring Boot application...
      - mvn package -DskipTests

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
